App_Blog/urls.py
from django.urls import path
from . import views as vw

app_name = 'AppBlog'

urlpatterns = [
    path('', vw.VW_posts, name='URL_posts'),
    path('post/<int:pk>/', vw.VW_post_detail, name='URL_post_detail'),
]

App_Portfolio/urls.py
from django.urls import path
from . import views as vw

urlpatterns = [
    path('', vw.VW_home, name='URL_home'),
    path('contact/', vw.VW_contact, name='URL_contact'),
]

PJ007_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_ROOT, MEDIA_URL
from App_Portfolio import views as vw

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Portfolio.urls')),
    path('blogs/', include('App_Blog.urls'), name='URL_blogs'),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

App_Blog/models.py
from django.db import models
import datetime

# Create your models here.
class MO_blogs(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='App_Blog/images')
    date = models.DateField(default = datetime.date.today)

    def __str__(self):
        return self.name

App_Portfolio/models.py
from django.db import models

# Create your models here.
class MO_projects(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to = 'App_Portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name

App_Blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import MO_blogs

# Create your views here.
def VW_posts(request):
    posts = MO_blogs.objects.all()
    return render(request, 'posts.html', {
        'posts': posts
    })

def VW_post_detail(request, pk):
    # post = MO_blogs.objects.get(id=request.GET.get('id'))
    # post = MO_blogs.objects.get(id=pk)
    post = get_object_or_404(MO_blogs, pk=pk)
    return render(request, 'post_detail.html', {
        'post': post
    })

App_Portfolio/views.py
from django.shortcuts import render
from .models import MO_projects

# Create your views here.
def VW_home(request):
    projects = MO_projects.objects.all()
    return render(request, 'home.html', {
        'projects': projects
    })

def VW_contact(request):
    return render(request, 'contact.html')

App_Blog/templates/post_detail.html
{% extends 'layouts/base.html' %} {% block content %}

<div class="container p-4">
  <h3>{{ post.name }}</h3>
  <h3 class="my-2 h5 text-muted">
    {% comment %} {{ post.date | date:"M, d, Y" | upper }} {% endcomment %}
    {{ post.date | date:"F jS Y" }}
  </h3>
  <img class="img-fluid" src="{{ post.image.url }}" alt="" />
  <p>{{ post.description | safe }}</p>
  
</div>

{% endblock %}

App_Blog/templates/posts.html
{% extends 'layouts/base.html' %}
{% block content %}

<h1>Posts</h1>

{% for post in posts %}
<div class="container p-3">
    <div class="card card-body">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid" src="{{ post.image.url }}" alt="">
            </div>
            <div class="col-9">
                <h3><a href="{% url 'AppBlog:URL_post_detail' pk=post.id %}">{{ post.name }}</a></h3>
                <caption>{{ post.date | date:"M, d, Y" | upper }}</caption>
                <p>{{ post.description | striptags | truncatechars:80 }}</p>

            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

App_Portfolio/templates/contact.html
{% extends 'layouts/base.html' %}
{% block content %}
    Contact Information
{% endblock %}

App_Portfolio/templates/home.html
{% extends 'layouts/base.html' %} {% load static %} {% block content %}

<section>
  <div class="container p-4 row">
    <div class="col-md-8 my-auto">
      <h1>I am <strong>ol5ra</strong></h1>
      <h3>I am FullStack Python Developer</h3>
      <p align="justify">{% lorem 2 b random %}</p>
      <a
        href="{% static 'files/pdf.pdf' %}"
        class="btn btn-primary btn-lg round-0 my-3"
      >
        Download CV
      </a>
    </div>
    <div class="col-md-4">
      <img
        class="img-fluid"
        src="{% static 'files/blondis.png' %}"
        alt="Blondis"
      />
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row my-4 text-center">
      <h1>My Projects.</h1>
      <p>
        Now, you are here. And must to pay for that. Now, you are here. And must
        to pay for that.
      </p>

      {% for project in projects %}
      <div class="col-md-4">
        <hr />
        <h3>{{ project.name }}</h3>
        <p>{{ project.description }}</p>
        <img
          class="img-fluid"
          src="{{ project.image.url }}"
          alt="Picture_project{{ project.id }}"
          data-image-width="900"
          data-image-height="1026"
        />
        {% if project.url %}
        <a href="{{ project.url }}">Go site</a>
        {% endif %}
        <br />
      </div>

      {% endfor %}
    </div>
    <br />
  </div>
</section>

<div class="container">
  <div class="row my-4 text-center">
    <h1>My Projects.</h1>
    <p class="card-project text-justify">
      Now, you are here. And must to pay for that. Now, you are here. And must
      to pay for that.
    </p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
      <div class="card card-project">
        {% comment %} <div class="card bg-black"> {% endcomment %}
            <img
            class="img-top"
            src="{{ project.image.url }}"
            alt="Picture_project{{ project.id }}"
            data-image-width="900"
            data-image-height="1026"
          />
        <div class="card-body">
          <h3>{{ project.name }}</h3>
          <p>{{ project.description }}</p>
          
          {% if project.url %}
          <a class= "btn btn-dark btn-sm" href="{{ project.url }}" target="_blank">Go site</a>
          {% endif %}
          <br />
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
  <br />
</div>

{% endblock %}

App_Portfolio/templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Boostrap 5 CC -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <!-- CSS  -->
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">

    <title>ol5ra</title>
</head>

<body>

    <header>
        <div>
            {% include 'partials/navbar.html' %}
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>



    <footer>
        <div>
            {% include 'partials/footer.html' %}
        </div>
    </footer>

    <!-- Boostrap 5 JS  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css.map"></script> -->

</body>

</html>

App_Portfolio/templates/partials/footer.html
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Form -->
    {% comment %}
    <section class="">
      {% endcomment %}
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example29" class="form-control" />
              <label class="form-label" for="form5Example29"
                >Email address</label
              >
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
      {% comment %}
    </section>
    {% endcomment %}
    <!-- Section: Form -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

App_Portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold" href="{% url 'URL_home' %}">ol5ra</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'AppBlog:URL_posts' %}"
            >Posts</a
          >
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'files/pdf.pdf' %}"
            target="_blank"
            >Download CV</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'URL_contact' %}">Contact</a>
        </li>
        <!-- 
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
      </ul>
    </div>
  </div>
</nav>